version: '3.7'

services:
  bot-dev:
    build: 
      context: .
      dockerfile: Dockerfile
      target: dev
    restart: always
    volumes:
      - ./src:/node/app/src
    container_name: nsk-tasks-bot-dev
    env_file:
      - .env.dev
    command: npm run dev
    ports:
      - "80:80"