version: '3.7'

services:
  bot:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - bot:/node/app/
    container_name: nsk-tasks-bot
    env_file:
      - .env
    command: npm run start
    ports:
      - "8080"
volumes:
  bot: