version: '3.7'

services:
  bot:
    build: 
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: always
    volumes:
      - ./src:/node/app/
    container_name: nsk-tasks-bot
    env_file:
      - .env
    command: npm run start
    ports:
      - "80:80"