version: '3.7'

services:
  bot-dev:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/node/app/
    container_name: nsk-tasks-bot-dev
    env_file:
      - .env.dev
    command: npm run start
    ports:
      - "8080:80"